### PR TITLE
Add jenkins slack notifications

### PR DESCRIPTION
**Pull request by lwsanty**

### CODE REVIEW

**Comment by jfontan** [comment]
I've restarted the tests. There's also this case in the boken api test:

```
    --- FAIL: TestAll/testPeriodicallyBrokenGithubAPI (0.09s)
        download_test.go:371: 
            	Error Trace:	download_test.go:371
            	            				download_test.go:138
            	Error:      	"Get https://github.com/apoliukh/awesome-sysadmin.git/info/refs?service=git-upload-pack: Forbidden" does not contain "Internal Server Error"
            	Test:       	TestAll/testPeriodicallyBrokenGithubAPI
```

**Comment by lwsanty** [comment]
yep, that's weird, I cannot reproduce it locally

**Comment by jfontan** [comment]
Another case:

```
    --- FAIL: TestAll/testPeriodicallyBrokenGithubAPI (0.10s)
        download_test.go:371: 
            	Error Trace:	download_test.go:371
            	            				download_test.go:138
            	Error:      	"Get https://github.com/MunGell/awesome-for-beginners.git/info/refs?service=git-upload-pack: Moved Permanently" does not contain "Internal Server Error"
            	Test:       	TestAll/testPeriodicallyBrokenGithubAPI
```

**Comment by lwsanty** [comment]
@jfontan fixed

**Pull request merged**
