### PR TITLE
github proxy tests

### PR DESCRIPTION
**Pull request by lwsanty**
add github proxy + extend discovery and download tests

Signed-off-by: lwsanty <lwsanty@gmail.com>

### CODE REVIEW

**Comment by lwsanty** [comment]
blocked by https://github.com/src-d/infrastructure/issues/1171

**Comment by jfontan** [comment]
This new tests need certificates to be configured in the system and they are always executed. While this is ok to do in travis VMs I'm not sure this should be a requirement in the developer's computer. `make test` fails.

I would either enable insecure communication for tests so the certs don't need to be installed in the computer or only execute these tests if explicitly asked for. One way to do this is moving the test to a new file and add a build tag on top:

```go
// +build proxy

package discovery

func TestProxyMockUps(t *testing.T) {
....
```

and calling `make` in travis script with `GO_TAGS` set

```yaml
- GO_TAGS=proxy make ci-script
```

Either option is OK for me but I would prefer if tests could be run in my computer without installing certs.

@mcarmonaa thoughts?

**Comment by lwsanty** [comment]
@jfontan I like the tags version

**Comment by mcarmonaa** [comment]
Other way could be just check for the environment variables the CI sets, so if for any reason you want to run those tests you just have to set the variables instead of rebuild the project:

```go
if os.Getenv("TRAVIS") != "" {
        t.Skip()
}
```

Anyway it's fine for me also the `tag` thing, not a strong preference for any of these solutions.

**Comment by lwsanty** [comment]
@mcarmonaa this one is the easiest, I will pick it if @jfontan is ok with it

**Comment by jfontan** [comment]
@lwsanty I believe there is a better way. When setting up the transport to use proxy you can configure `Transport`'s to accept insecure certificates:

https://golang.org/pkg/net/http/#Transport
https://golang.org/pkg/crypto/tls/#Config

Something like:

```go
// SetTransportProxy changes http.DefaultTransport to the one that uses current server as a proxy
func SetTransportProxy() error {
	u, err := url.Parse(URL)
	if err != nil {
		return err
	}

	http.DefaultTransport = &http.Transport{
		Proxy: http.ProxyURL(u),
		// Disable HTTP/2.
		TLSNextProto: make(map[string]func(authority string, c *tls.Conn) http.RoundTripper),
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}

	return nil
}
```

**Comment by lwsanty** [comment]
@jfontan got it! I will check it tomorrow!

**Pull request merged**
